version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
    assignees:
      - tandemdude
    reviewers:
      - tandemdude
    rebase-strategy: auto
    target-branch: master
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    assignees:
      - tandemdude
    reviewers:
      - tandemdude
    rebase-strategy: auto
    target-branch: master
